apiVersion: v1
kind: Service
metadata:
  namespace: namespace-workflow-1708364291610
  name: ad-demo
spec:
  type: LoadBalancer
  selector:
    app: ad-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
