apiVersion: v1
kind: Service
metadata:
  name: ad_demo
  namespace: namespace-workflow-1708364291610
spec:
  type: LoadBalancer
  selector:
    app: ad_demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
